// <auto-generated />
using CS335_A1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS335_A1.Migrations
{
    [DbContext(typeof(WebAPIDBContext))]
    partial class WebAPIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");
#pragma warning restore 612, 618
        
        modelBuilder.Entity("CS335-A1.Models.Staff", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("Tel")
                   .HasColumnType("TEXT");

                b.Property<string>("Url")
                   .HasColumnType("TEXT");

                b.Property<string>("Research")
                   .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Staff");
            });
            modelBuilder.Entity("CS335-A1.Models.Products", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("Price")
                    .HasColumnType("DOUBLE");

                b.HasKey("Id");

                b.ToTable("Products");
            });
            modelBuilder.Entity("CS335-A1.Models.Comments", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Time")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");
                
                b.Property<string>("IP")
                    .IsRequired()
                    .HasColumnType("TEXT");
                
                b.HasKey("Id");

                b.ToTable("Comments");
            });
#pragma warning restore 612, 618
        }
    }
}